### ISSUE TITLE
Block - new options

### ISSUE THREAD

**Issue by hetmann** [react-ui-kit/expo-ui-kit#32]
- [x] Add new prop named **scroll** to render **ScrollView** component
- [x] when **row** option is selected, **flex** value should be 0 by default
- [x] add new props named **width** for View width style and **height** for View height style

**Comment by talesdsp** [comment]
Hey @hetmann. Just added these new features on the last PR #41 but I'm now thinking that the Block component just accepts a huge amount of props. It can be styling, event handlers, and now that list from ScrollView. For someone using this lib can be hard to remember everything that could be passed.
Maybe it is time to start adding typescript?

**Comment by hetmann** [comment]
> Hey @hetmann. Just added these new features on the last PR #41 but I'm now thinking that the Block component just accepts a huge amount of props. It can be styling, event handlers, and now that list from ScrollView. For someone using this lib can be hard to remember everything that could be passed.
> Maybe it is time to start adding typescript?

You are right. I had this in my backlog and right now I created the issue #42 .
I was thinking that a type definition for each component would work for now.
