### ISSUE TITLE
Module parse failed?

### ISSUE THREAD

**Issue by talesdsp** [react-ui-kit/expo-ui-kit#61]
Out of curiosity, I searched for the [bundled size](https://bundlephobia.com/result?p=expo-ui-kit) and the package throws this error:

`/tmp/tmp-build/packages/build-expo-ui-kit-6-C/node_modules/expo-ui-kit/src/Input.js 130:4 Module parse failed: Unexpected token (130:4) File was processed with these loaders: * ./node_modules/shebang-loader/index.js You may need an additional loader to handle the result of these loaders. | | return ( > <TextInput | ref={internalRef} | {...props} @ /tmp/tmp-build/packages/build-expo-ui-kit-6-C/node_modules/expo-ui-kit/src/index.js 4:0-28 7:0-44 @ /tmp/tmp-build/packages/build-expo-ui-kit-6-C/node_modules/expo-ui-kit/index.js @ /tmp/tmp-build/packages/build-expo-ui-kit-6-C/index.js`

**Comment by hetmann** [comment]
@talesdsp I have no idea :) but let me merge the dev branch into master. The expo-ui-kit package is at version 0.1.4 on npmjs.com

**Comment by hetmann** [comment]
@talesdsp I think the error is because there are no dependencies on package.json I'll to a fix and version update.

**Comment by hetmann** [comment]
@talesdsp same error after adding react-native on deps

**Comment by talesdsp** [comment]
Tested on [packagephobia](https://packagephobia.now.sh/) and works fine.

The problem is out of our scope and depends on them using the correct babel-loader https://github.com/pastelsky/bundlephobia/issues/279

I will remove the RN deps
