### ISSUE TITLE
Input value not showing

### ISSUE THREAD

**Issue by VaMusaka** [react-ui-kit/expo-ui-kit#80]
Hi 

I have just recently started using expo-ui-kit, which is awesome by the way 👍 . I only have a slight issue with the Input component at the moment. 

When l have a value set in state this is not showing in when i use `<Input value={valueFromState} />`  as it normally would when using the `react-native` `<TextInput value={valueFromState}  />` component. 

To demonstrate this issue l have created a [snack](https://snack.expo.io/@pmusaka/input-value-not-working)  with the example code of the 2 input explained above. 

Is there a work around to this problem or is there some thing l am missing ? 

Please Help,
Thanks in advance

**Comment by hetmann** [comment]
@VaMusaka thank you for pointing this out. For that to work you should use **defaultValue** prop instead of **value** prop

```jsx
<Input
   defaultValue={value}
   onChangeText={(value) => setValue(value)}
   style={styles.input}
/>
```

More info on RN docs https://reactnative.dev/docs/textinput#defaultvalue
